### ISSUE TITLE
False positive when browser internal pdf is enabled

### ISSUE THREAD

**Issue by TLeiter** [fingerprintjs/BotD#135]
In Edge and Chrome if the setting "Open PDF in Chrome/Edge" is enabled (Settings > Privacy and security > Site settings > Additional content settings > PDF documents.), then the value navigator.plugins is empty which evalute the bot test to true.

**Comment by TLeiter** [comment]
Tested and not currently fixed.

**Comment by xnerhu** [comment]
> Tested and not currently fixed.

Can you make sure you are on the latest version? Also please, send me botd snapshot from playgrond https://fingerprintjs.github.io/BotD/main/

**Comment by TLeiter** [comment]
Hello,

Hre is the snapshot from the playground:

{"isError":false,"collectionTime":20.199999928474426,"detectionTime":21.299999952316284,"detectionResult":{"bot":true,"botKind":"headless_chrome"},"detectedBot":"headless_chrome","collectedData":{"process":{"state":-1,"error":"BotdError: window.process is undefined"},"userAgent":{"value":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36","state":0},"appVersion":{"value":"5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36","state":0},"rtt":{"value":0,"state":0},"windowSize":{"value":{"outerWidth":2048,"outerHeight":1152,"innerWidth":2048,"innerHeight":1043},"state":0},"pluginsLength":{"value":0,"state":0},"pluginsArray":{"value":true,"state":0},"errorTrace":{"value":"TypeError: Cannot read properties of null (reading '0')\n    at errorTrace ([https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:27921)\n](https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:27921)/n)    at n.<anonymous> ([https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:33455)\n](https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:33455)/n)    at [https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:21466\n](https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:21466/n)    at Object.next ([https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:21571)\n](https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:21571)/n)    at [https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:20487\n](https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:20487/n)    at new Promise (<anonymous>)\n    at e ([https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:20232)\n](https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:20232)/n)    at [https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:33292\n](https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:33292/n)    at Array.map (<anonymous>)\n    at n.<anonymous> ([https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:33268)","state":0},"productSub":{"value":"20030107","state":0},"windowExternal":{"value":"[object](https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:33268)%22,%22state%22:0%7d,%22productSub%22:%7b%22value%22:%2220030107%22,%22state%22:0%7d,%22windowExternal%22:%7b%22value%22:%22%5bobject) External]","state":0},"mimeTypesConsistent":{"value":true,"state":0},"evalLength":{"value":33,"state":0},"webGL":{"value":{"vendor":"WebKit","renderer":"WebKit WebGL"},"state":0},"webDriver":{"value":false,"state":0},"languages":{"value":[["en-US"]],"state":0},"documentElementKeys":{"value":["lang"],"state":0},"functionBind":{"value":"function bind() { [native code] }","state":0},"distinctiveProps":{"value":{"awesomium":false,"cef":false,"cefsharp":false,"coachjs":false,"fminer":false,"geb":false,"nightmarejs":false,"phantomas":false,"phantomjs":false,"rhino":false,"selenium":false,"webdriverio":false,"webdriver":false,"headless_chrome":false},"state":0},"notificationPermissions":{"value":false,"state":0}},"detectorsResults":{"detectAppVersion":{"bot":false},"detectDocumentAttributes":{"bot":false},"detectErrorTrace":{"bot":false},"detectEvalLengthInconsistency":{"bot":false},"detectFunctionBind":{"bot":false},"detectLanguagesLengthInconsistency":{"bot":false},"detectNotificationPermissions":{"bot":false},"detectPluginsArray":{"bot":false},"detectPluginsLengthInconsistency":{"bot":true,"botKind":"headless_chrome"},"detectProcess":{"bot":false},"detectUserAgent":{"bot":false},"detectWebDriver":{"bot":false},"detectWebGL":{"bot":false},"detectWindowExternal":{"bot":false},"detectWindowSize":{"bot":false},"detectMimeTypesConsistent":{"bot":false},"detectProductSub":{"bot":false},"detectDistinctiveProperties":{"bot":false}},"debugData":{"browserEngineKind":"chromium","browserKind":"chrome","documentFocus":true,"mozAppearanceSupport":false,"isAndroid":false,"isDesktopWebKit":false}}

**Comment by xnerhu** [comment]
@TLeiter I added support for detecting edge as `BrowserKind`, so it should fix the issue

**Comment by AnastasiaPlague** [comment]
We are encountering the same problem using the playground on latest Chrome, Chrome 119, Chrome 116. Steps are the same as the issue author described.

Would you look into it again?

```json 
{
  "isError": false,
  "collectionTime": 45.8000000002794,
  "detectionTime": 47.3000000002794,
  "detectionResult": { "bot": true, "botKind": "headless_chrome" },
  "detectedBot": "headless_chrome",
  "collectedData": {
    "process": {
      "state": -1,
      "error": "BotdError: window.process is undefined"
    },
    "android": { "value": false, "state": 0 },
    "browserKind": { "value": "chrome", "state": 0 },
    "browserEngineKind": { "value": "chromium", "state": 0 },
    "documentFocus": { "value": true, "state": 0 },
    "userAgent": {
      "value": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
      "state": 0
    },
    "appVersion": {
      "value": "5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
      "state": 0
    },
    "rtt": { "value": 100, "state": 0 },
    "windowSize": {
      "value": {
        "outerWidth": 1920,
        "outerHeight": 1040,
        "innerWidth": 1920,
        "innerHeight": 953
      },
      "state": 0
    },
    "pluginsLength": { "value": 0, "state": 0 },
    "pluginsArray": { "value": true, "state": 0 },
    "errorTrace": {
      "value": "TypeError: Cannot read properties of null (reading '0')\n    at errorTrace (https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:45891)\n    at https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:39573\n    at https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:38227\n    at Object.next (https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:38332)\n    at https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:37248\n    at new Promise (<anonymous>)\n    at e (https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:36993)\n    at https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:39410\n    at Array.map (<anonymous>)\n    at https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:39386",
      "state": 0
    },
    "productSub": { "value": "20030107", "state": 0 },
    "windowExternal": { "value": "[object External]", "state": 0 },
    "mimeTypesConsistent": { "value": true, "state": 0 },
    "evalLength": { "value": 33, "state": 0 },
    "webGL": {
      "value": { "vendor": "WebKit", "renderer": "WebKit WebGL" },
      "state": 0
    },
    "webDriver": { "value": false, "state": 0 },
    "languages": { "value": [["ru-RU"]], "state": 0 },
    "documentElementKeys": { "value": ["lang"], "state": 0 },
    "functionBind": {
      "value": "function bind() { [native code] }",
      "state": 0
    },
    "distinctiveProps": {
      "value": {
        "awesomium": false,
        "cef": false,
        "cefsharp": false,
        "coachjs": false,
        "fminer": false,
        "geb": false,
        "nightmarejs": false,
        "phantomas": false,
        "phantomjs": false,
        "rhino": false,
        "selenium": false,
        "webdriverio": false,
        "webdriver": false,
        "headless_chrome": false
      },
      "state": 0
    },
    "notificationPermissions": { "value": false, "state": 0 }
  },
  "detectorsResults": {
    "detectAppVersion": { "bot": false },
    "detectDocumentAttributes": { "bot": false },
    "detectErrorTrace": { "bot": false },
    "detectEvalLengthInconsistency": { "bot": false },
    "detectFunctionBind": { "bot": false },
    "detectLanguagesLengthInconsistency": { "bot": false },
    "detectNotificationPermissions": { "bot": false },
    "detectPluginsArray": { "bot": false },
    "detectPluginsLengthInconsistency": {
      "bot": true,
      "botKind": "headless_chrome"
    },
    "detectProcess": { "bot": false },
    "detectUserAgent": { "bot": false },
    "detectWebDriver": { "bot": false },
    "detectWebGL": { "bot": false },
    "detectWindowExternal": { "bot": false },
    "detectWindowSize": { "bot": false },
    "detectMimeTypesConsistent": { "bot": false },
    "detectProductSub": { "bot": false },
    "detectDistinctiveProperties": { "bot": false }
  },
  "debugData": {
    "browserEngineKind": "chromium",
    "browserKind": "chrome",
    "browserVersion": { "major": 120, "minor": 0 },
    "documentFocus": true,
    "mozAppearanceSupport": false,
    "isAndroid": false,
    "isDesktopWebKit": false,
    "isIPad": true
  }
}
```

**Comment by xnerhu** [comment]
> AnastasiaPlague

Of course.

**Comment by hwangzhiming** [comment]
We are encountering the same problem, I think detectPluginsLengthInconsistency is wrong in this case @xnerhu 
![image](https://github.com/fingerprintjs/BotD/assets/1012374/64ff637c-e5a5-4ee0-97a9-4bb1819057e2)

**Comment by hwangzhiming** [comment]
If the user sets `Download PDFs` instead of `Open PDFs in Chrome` in Chrome, the length of the plugin array will be 0, causing a false positive for headless detection.  any solutions?
![image](https://github.com/fingerprintjs/BotD/assets/1012374/9d1dc2d4-f935-4e2e-9f05-ad10dc8babeb)

**Comment by nketkar** [comment]
I am also seeing a lot of false positives on the length of the Plugin array being 0. It appears the navigator.plugins array is deprecated anyways: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/plugins

Can this rule be removed for good?

**Comment by Jackenmen** [comment]
I'm also running into this one as a user of one of the sites that use this lib, took me a while to figure out why, wish I knew that the lib has a playground :smile: 

<details>
<summary>logs</summary>

```json
{"isError":false,"collectionTime":7.300000000745058,"detectionTime":7.400000002235174,"detectionResult":{"bot":true,"botKind":"headless_chrome"},"detectedBot":"headless_chrome","collectedData":{"process":{"state":-1,"error":"BotdError: window.process is undefined"},"android":{"value":false,"state":0},"browserKind":{"value":"chrome","state":0},"browserEngineKind":{"value":"chromium","state":0},"documentFocus":{"value":true,"state":0},"userAgent":{"value":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36","state":0},"appVersion":{"value":"5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36","state":0},"rtt":{"value":50,"state":0},"windowSize":{"value":{"outerWidth":1920,"outerHeight":1051,"innerWidth":1920,"innerHeight":964},"state":0},"pluginsLength":{"value":0,"state":0},"pluginsArray":{"value":true,"state":0},"errorTrace":{"value":"TypeError: Cannot read properties of null (reading '0')\n    at errorTrace (https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:45891)\n    at https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:39573\n    at https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:38227\n    at Object.next (https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:38332)\n    at https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:37248\n    at new Promise (<anonymous>)\n    at e (https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:36993)\n    at https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:39410\n    at Array.map (<anonymous>)\n    at https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:39386","state":0},"productSub":{"value":"20030107","state":0},"windowExternal":{"value":"[object External]","state":0},"mimeTypesConsistent":{"value":true,"state":0},"evalLength":{"value":33,"state":0},"webGL":{"value":{"vendor":"WebKit","renderer":"WebKit WebGL"},"state":0},"webDriver":{"value":false,"state":0},"languages":{"value":[["en-US"]],"state":0},"documentElementKeys":{"value":["lang"],"state":0},"functionBind":{"value":"function bind() { [native code] }","state":0},"distinctiveProps":{"value":{"awesomium":false,"cef":false,"cefsharp":false,"coachjs":false,"fminer":false,"geb":false,"nightmarejs":false,"phantomas":false,"phantomjs":false,"rhino":false,"selenium":false,"webdriverio":false,"webdriver":false,"headless_chrome":false},"state":0},"notificationPermissions":{"value":false,"state":0}},"detectorsResults":{"detectAppVersion":{"bot":false},"detectDocumentAttributes":{"bot":false},"detectErrorTrace":{"bot":false},"detectEvalLengthInconsistency":{"bot":false},"detectFunctionBind":{"bot":false},"detectLanguagesLengthInconsistency":{"bot":false},"detectNotificationPermissions":{"bot":false},"detectPluginsArray":{"bot":false},"detectPluginsLengthInconsistency":{"bot":true,"botKind":"headless_chrome"},"detectProcess":{"bot":false},"detectUserAgent":{"bot":false},"detectWebDriver":{"bot":false},"detectWebGL":{"bot":false},"detectWindowExternal":{"bot":false},"detectWindowSize":{"bot":false},"detectMimeTypesConsistent":{"bot":false},"detectProductSub":{"bot":false},"detectDistinctiveProperties":{"bot":false}},"debugData":{"browserEngineKind":"chromium","browserKind":"chrome","browserVersion":{"major":127,"minor":0},"documentFocus":true,"mozAppearanceSupport":false,"isAndroid":false,"isDesktopWebKit":false,"isIPad":true}}
```

</details>

**Comment by Santas** [comment]
Chrome 131 still affected with this PDF setting.

**Comment by ivomasterche** [comment]
Same here. Allowing chrome to open PDF fixes the false positive
Log with downloading pdf:

{"isError":false,"collectionTime":91.5,"detectionTime":91.70000000018626,"detectionResult":{"bot":true,"botKind":"headless_chrome"},"detectedBot":"headless_chrome","collectedData":{"process":{"state":-1,"error":"BotdError: window.process is undefined"},"android":{"value":false,"state":0},"browserKind":{"value":"chrome","state":0},"browserEngineKind":{"value":"chromium","state":0},"documentFocus":{"value":true,"state":0},"userAgent":{"value":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36","state":0},"appVersion":{"value":"5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36","state":0},"rtt":{"value":50,"state":0},"windowSize":{"value":{"outerWidth":1920,"outerHeight":1040,"innerWidth":1920,"innerHeight":953},"state":0},"pluginsLength":{"value":0,"state":0},"pluginsArray":{"value":true,"state":0},"errorTrace":{"value":"TypeError: Cannot read properties of null (reading '0')\n    at errorTrace (https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:45895)\n    at https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:39515\n    at https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:38324\n    at Object.next (https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:38429)\n    at https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:37345\n    at new Promise (<anonymous>)\n    at e (https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:37090)\n    at https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:39352\n    at Array.map (<anonymous>)\n    at https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:39328","state":0},"productSub":{"value":"20030107","state":0},"windowExternal":{"value":"[object External]","state":0},"mimeTypesConsistent":{"value":true,"state":0},"evalLength":{"value":33,"state":0},"webGL":{"value":{"vendor":"WebKit","renderer":"WebKit WebGL"},"state":0},"webDriver":{"value":false,"state":0},"languages":{"value":[["bg-BG"]],"state":0},"documentElementKeys":{"value":["lang"],"state":0},"functionBind":{"value":"function bind() { [native code] }","state":0},"distinctiveProps":{"value":{"awesomium":false,"cef":false,"cefsharp":false,"coachjs":false,"fminer":false,"geb":false,"nightmarejs":false,"phantomas":false,"phantomjs":false,"rhino":false,"selenium":false,"webdriverio":false,"webdriver":false,"headless_chrome":false},"state":0},"notificationPermissions":{"value":false,"state":0}},"detectorsResults":{"detectAppVersion":{"bot":false},"detectDocumentAttributes":{"bot":false},"detectErrorTrace":{"bot":false},"detectEvalLengthInconsistency":{"bot":false},"detectFunctionBind":{"bot":false},"detectLanguagesLengthInconsistency":{"bot":false},"detectNotificationPermissions":{"bot":false},"detectPluginsArray":{"bot":false},"detectPluginsLengthInconsistency":{"bot":true,"botKind":"headless_chrome"},"detectProcess":{"bot":false},"detectUserAgent":{"bot":false},"detectWebDriver":{"bot":false},"detectWebGL":{"bot":false},"detectWindowExternal":{"bot":false},"detectWindowSize":{"bot":false},"detectMimeTypesConsistent":{"bot":false},"detectProductSub":{"bot":false},"detectDistinctiveProperties":{"bot":false}},"debugData":{"browserEngineKind":"chromium","browserKind":"chrome","browserVersion":{"major":131,"minor":0},"documentFocus":true,"mozAppearanceSupport":false,"isAndroid":false,"isDesktopWebKit":false,"isIPad":true}}

**Comment by peaeater** [comment]
I have another false positive example when Chrome 136 is set to "Download PDFs" instead of "Open PDFs in Chrome". 

```json
{"isError":false,"collectionTime":62.70000000111759,"detectionTime":63.30000000074506,"detectionResult":{"bot":true,"botKind":"headless_chrome"},"detectedBot":"headless_chrome","collectedData":{"process":{"state":-1,"error":"BotdError: window.process is undefined"},"android":{"value":false,"state":0},"browserKind":{"value":"chrome","state":0},"browserEngineKind":{"value":"chromium","state":0},"documentFocus":{"value":true,"state":0},"userAgent":{"value":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36","state":0},"appVersion":{"value":"5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36","state":0},"rtt":{"value":100,"state":0},"windowSize":{"value":{"outerWidth":1914,"outerHeight":1026,"innerWidth":1920,"innerHeight":911},"state":0},"pluginsLength":{"value":0,"state":0},"pluginsArray":{"value":true,"state":0},"errorTrace":{"value":"TypeError: Cannot read properties of null (reading '0')\n    at errorTrace ([https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:45895)\n](https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:45895)/n)    at [https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:39515\n](https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:39515/n)    at [https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:38324\n](https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:38324/n)    at Object.next ([https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:38429)\n](https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:38429)/n)    at [https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:37345\n](https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:37345/n)    at new Promise (<anonymous>)\n    at e ([https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:37090)\n](https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:37090)/n)    at [https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:39352\n](https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:39352/n)    at Array.map (<anonymous>)\n    at [https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:39328","state":0},"productSub":{"value":"20030107","state":0},"windowExternal":{"value":"[object](https://fingerprintjs.github.io/BotD/main/main.bundle.js:1:39328%22,%22state%22:0%7d,%22productSub%22:%7b%22value%22:%2220030107%22,%22state%22:0%7d,%22windowExternal%22:%7b%22value%22:%22%5bobject) External]","state":0},"mimeTypesConsistent":{"value":true,"state":0},"evalLength":{"value":33,"state":0},"webGL":{"value":{"vendor":"WebKit","renderer":"WebKit WebGL"},"state":0},"webDriver":{"value":false,"state":0},"languages":{"value":[["en-GB"]],"state":0},"documentElementKeys":{"value":["lang"],"state":0},"functionBind":{"value":"function bind() { [native code] }","state":0},"distinctiveProps":{"value":{"awesomium":false,"cef":false,"cefsharp":false,"coachjs":false,"fminer":false,"geb":false,"nightmarejs":false,"phantomas":false,"phantomjs":false,"rhino":false,"selenium":false,"webdriverio":false,"webdriver":false,"headless_chrome":false},"state":0},"notificationPermissions":{"value":false,"state":0}},"detectorsResults":{"detectAppVersion":{"bot":false},"detectDocumentAttributes":{"bot":false},"detectErrorTrace":{"bot":false},"detectEvalLengthInconsistency":{"bot":false},"detectFunctionBind":{"bot":false},"detectLanguagesLengthInconsistency":{"bot":false},"detectNotificationPermissions":{"bot":false},"detectPluginsArray":{"bot":false},"detectPluginsLengthInconsistency":{"bot":true,"botKind":"headless_chrome"},"detectProcess":{"bot":false},"detectUserAgent":{"bot":false},"detectWebDriver":{"bot":false},"detectWebGL":{"bot":false},"detectWindowExternal":{"bot":false},"detectWindowSize":{"bot":false},"detectMimeTypesConsistent":{"bot":false},"detectProductSub":{"bot":false},"detectDistinctiveProperties":{"bot":false}},"debugData":{"browserEngineKind":"chromium","browserKind":"chrome","browserVersion":{"major":136,"minor":0},"documentFocus":true,"mozAppearanceSupport":false,"isAndroid":false,"isDesktopWebKit":false,"isIPad":true}}
```
